### ISSUE TITLE
Compilation Chapter 6

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Hands-On-Design-Patterns-with-C-#1]
How are the files in chapter 6 to be compiled? `smartptr_extra.C` doesn't have a main function and `smartptr.C` has unresolved `externs`.

Kind regards.

**Comment by fpikus** [comment]
You need both. That's the point of the exercise, to measure the impact of function calls that are in a separate compilation unit and, therefore, are definitely not inlined (unless you enable whole-program optimization). Here is how you can build it, with GCC (use the library and include paths for your own system):
g++-7 smartptr.C smartptr_extra.C -I../gbench/include -g -O4 -I. -Wall -Wextra -Werror -pedantic -mavx2 --std=c++17 ../gbench/lib/libbenchmark.a -lpthread -lrt -lm -o smartptr

**Comment by ghost** [comment]
Ok. Cool! Read the chapter a few days ago but didn't compile it and got desperate last night to catch up with all those files that use the Google benchmark library. I knew I would look stupid if you'd answer the question. 😀

This awesome book needs a second read for me anyway. I can't get all of it in my head the first time.

Thanks a lot for your quick reply and for writing the book!
