### ISSUE TITLE
get compile error on 04c_visitor_template.cpp

### ISSUE THREAD

**Issue by OrenHg** [PacktPublishing/Hands-On-Design-Patterns-with-C-#2]
i use following command to compile '04c_visitor_template.cpp' code 
`g++ std=c++14 04c_visitor_template.cpp` 
but get following error:

> 04c_visitor_template.cpp: In instantiation of ‘void LambdaVisitor<Base, Visitor<T1>, std::tuple<_Tail ...> >::visit(T1*) [with Base = Visitor<Cat, Dog>; T1 = Dog; F = {walk(Pet&)::<lambda(Cat*)>, walk(Pet&)::<lambda(Dog*)>}]’:
04c_visitor_template.cpp:54:10:   required from here
04c_visitor_template.cpp:54:52: error: cannot convert ‘Dog*’ to ‘Cat*’
   54 |     void visit(T1* t) override {  this->operator()(t); }
      |                                                    ^
      |                                                    |
      |                                                    Dog*
04c_visitor_template.cpp:112:13: note:   initializing argument 1 of ‘walk(Pet&)::<lambda(Cat*)>’
  112 |             [](Cat* c) { std::cout << "Let the " << c->color() << " cat out" << std::endl; },
      |             ^

i don't know how to fix it

**Comment by rajat-packt** [comment]
Sorry for the late reply, we are trying to reach out to the author and we'll update you as soon as we hear from them.

**Comment by rajat-packt** [comment]
@OrenHg the author has looked into the matter and pushed the updated file in the repo.
Closing this issue now.
